DELIMITER $$

DROP PROCEDURE IF EXISTS `INSERT_MOVIE` $$
CREATE PROCEDURE INSERT_MOVIE(IN ID VARCHAR(10), TITLE VARCHAR(100), `YEAR` INT,  DIRECTOR VARCHAR(100), STAR VARCHAR(100), )
BEGIN
  INSERT INTO movies VALUES (ID, TITLE, YEAR, DIRECTOR);
  INSERT INTO stars_in_movies VALUES ()
end $$