DELIMITER $$

DROP PROCEDURE IF EXISTS `INSERT_MOVIE` $$

CREATE PROCEDURE INSERT_MOVIE
  (
  TITLE VARCHAR(100), `YEAR` INT,  DIRECTOR VARCHAR(100), STAR VARCHAR(100), GENRE VARCHAR(32)
  )
BEGIN
  INSERT INTO movies VALUES (ID, TITLE, YEAR, DIRECTOR);
  INSERT INTO genres_in_movies VALUES ()
end $$


DROP FUNCTION IF EXISTS `SAME_MOVIE` $$
CREATE FUNCTION SAME_MOVIE
(
  TITLE VARCHAR(100), `YEAR` INT, DIRECTOR VARCHAR(100)
)
RETURNS BOOL
BEGIN
  SELECT * FROM movies WHERE director=DIRECTOR AND year=YEAR AND title=TITLE;
end $$